package com.College_project.project.enums;

public enum AlertType {
    BUDGET_WARNING,
    BILL_REMINDER,
    UNUSUAL_SPENDING,
    GOAL_ACHIEVED,
    FINANCIAL_INSIGHT,
    RECEIPT_PROCESSED,
    TRANSACTION_UPDATE,
    INVESTMENT_UPDATE,
    INVESTMENT_ADVICE
}
