package com.College_project.project.service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import com.College_project.project.DTOs.InvestmentAdviceRequest;
import com.College_project.project.DTOs.InvestmentAdviceResponse;
import com.College_project.project.DTOs.PortfolioAllocation;
import com.College_project.project.enums.TransactionType;
import com.College_project.project.models.Investment;
import com.College_project.project.models.Transaction;
import com.College_project.project.models.User;
import com.College_project.project.repository.UserRepository;
import com.College_project.project.repository.investmentRepository;
import com.College_project.project.repository.transactionRepository;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import jakarta.annotation.PostConstruct;

@Service
public class AIInvestmentAdviceService {
    
    @Autowired
    private investmentRepository investmentRepository;
    
    @Autowired
    private transactionRepository transactionRepository;
    
    @Autowired
    private UserRepository userRepository;
    
    @Autowired
    private InvestmentAdviceService fallbackAdviceService;
    
    @Value("${openrouter.api.key:}")
    private String apiKey;

    @Value("${ollama.url:http://localhost:11434}")
    private String ollamaUrl;

    @Value("${ollama.model:qwen2.5:3b}")
    private String ollamaModel;

    @Value("${openrouter.model:stepfun/step-3.5-flash}")
    private String openRouterModel;
    
    private final RestTemplate restTemplate = createRestTemplateWithTimeout(3000, 120000);

    private static RestTemplate createRestTemplateWithTimeout(int connectTimeoutMs, int readTimeoutMs) {
        org.springframework.http.client.SimpleClientHttpRequestFactory factory = new org.springframework.http.client.SimpleClientHttpRequestFactory();
        factory.setConnectTimeout(connectTimeoutMs);
        factory.setReadTimeout(readTimeoutMs);
        return new RestTemplate(factory);
    }
    private final ObjectMapper objectMapper = new ObjectMapper();
    
    @PostConstruct
    public void init() {
        System.out.println("========== AI Investment Advice Service Initialized ==========");
        if (apiKey != null && !apiKey.isEmpty()) {
            System.out.println("✅ AI Investment Advice is ENABLED");
        } else {
            System.out.println("⚠️ AI Investment Advice is DISABLED (no API key) - using fallback only");
        }
    }
    
    /**
     * Main method - tries local AI, then cloud AI, then rule-based fallback
     */
    public InvestmentAdviceResponse getInvestmentAdviceWithAIFallback(Long userId, InvestmentAdviceRequest request) {
        System.out.println("========== Investment Advice Request ==========");
        List<String> aiFailures = new ArrayList<>();
        
        // 1. Try local Ollama first
        try {
            System.out.println("Attempting local Ollama investment advice...");
            InvestmentAdviceResponse response = getLocalAIInvestmentAdvice(userId, request);
            response.setMethodUsed("AI");
            response.setMethodDetails("Generated by local Ollama model: " + ollamaModel);
            return response;
        } catch (Exception e) {
            System.err.println("Local Ollama advice failed: " + e.getMessage());
            aiFailures.add("Ollama: " + e.getMessage());
        }

        // 2. Try OpenRouter cloud if key exists
        if (apiKey != null && !apiKey.isEmpty()) {
            try {
                System.out.println("Attempting OpenRouter AI investment advice...");
                InvestmentAdviceResponse response = getAIInvestmentAdvice(userId, request);
                response.setMethodUsed("AI");
                response.setMethodDetails("Generated by OpenRouter model: " + openRouterModel);
                return response;
            } catch (Exception e) {
                System.err.println("OpenRouter AI advice failed: " + e.getMessage());
                aiFailures.add("OpenRouter: " + e.getMessage());
            }
        } else {
            System.out.println("No OpenRouter API key configured. Skipping cloud AI.");
            aiFailures.add("OpenRouter: API key is not configured");
        }
        
        // 3. Final fallback: Rule-based advice
        System.out.println("Using rule-based fallback advice...");
        InvestmentAdviceResponse fallbackResponse = fallbackAdviceService.getInvestmentAdvice(userId, request);
        fallbackResponse.setMethodUsed("RULE");
        fallbackResponse.setMethodDetails("AI unavailable. Fallback reason(s): " + String.join(" | ", aiFailures));
        return fallbackResponse;
    }

    public InvestmentAdviceResponse getInvestmentAdviceAIOnly(Long userId, InvestmentAdviceRequest request) {
        System.out.println("========== AI-Only Investment Advice Request ==========");
        List<String> aiFailures = new ArrayList<>();

        try {
            System.out.println("Attempting local Ollama investment advice...");
            InvestmentAdviceResponse response = getLocalAIInvestmentAdvice(userId, request);
            response.setMethodUsed("AI");
            response.setMethodDetails("Generated by local Ollama model: " + ollamaModel);
            return response;
        } catch (Exception e) {
            System.err.println("Local Ollama advice failed: " + e.getMessage());
            aiFailures.add("Ollama: " + e.getMessage());
        }

        if (apiKey != null && !apiKey.isEmpty()) {
            try {
                System.out.println("Attempting OpenRouter AI investment advice...");
                InvestmentAdviceResponse response = getAIInvestmentAdvice(userId, request);
                response.setMethodUsed("AI");
                response.setMethodDetails("Generated by OpenRouter model: " + openRouterModel);
                return response;
            } catch (Exception e) {
                System.err.println("OpenRouter AI advice failed: " + e.getMessage());
                aiFailures.add("OpenRouter: " + e.getMessage());
            }
        } else {
            aiFailures.add("OpenRouter: API key is not configured");
        }

        throw new RuntimeException("AI investment advice is unavailable. " + String.join(" | ", aiFailures));
    }
    
    private InvestmentAdviceResponse getLocalAIInvestmentAdvice(Long userId, InvestmentAdviceRequest request) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        String financialData = gatherFinancialData(user, request);
        String prompt = buildInvestmentPrompt(financialData, request);
        
        String ollamaResponse = callOllamaAPI(prompt);
        return parseAIResponse(ollamaResponse, request);
    }
    
    private String callOllamaAPI(String prompt) {
        try {
            String url = ollamaUrl + "/api/generate";
            
            Map<String, Object> requestBody = new HashMap<>();
            requestBody.put("model", ollamaModel);
            requestBody.put("prompt", prompt);
            requestBody.put("stream", false);
            
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            
            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, headers);
            
            ResponseEntity<String> response = restTemplate.exchange(
                url, HttpMethod.POST, entity, String.class);
            
            if (response.getStatusCode() == HttpStatus.OK) {
                JsonNode json = objectMapper.readTree(response.getBody());
                return json.path("response").asText();
            } else {
                throw new RuntimeException("Ollama returned " + response.getStatusCode());
            }
        } catch (Exception e) {
            throw new RuntimeException("Ollama call failed: " + e.getMessage());
        }
    }
    
    /**
     * AI-powered investment advice using OpenRouter
     */

    
    private InvestmentAdviceResponse getAIInvestmentAdvice(Long userId, InvestmentAdviceRequest request) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found"));
        
        // Gather user financial data
        String financialData = gatherFinancialData(user, request);
        
        // Build AI prompt
        String prompt = buildInvestmentPrompt(financialData, request);
        
        // Call AI API
        String aiResponse = callOpenRouterAPI(prompt);
        
        // Parse and return AI response
        return parseAIResponse(aiResponse, request);
    }
    
    private String gatherFinancialData(User user, InvestmentAdviceRequest request) {
        // Get last 6 months of transactions
        LocalDate sixMonthsAgo = LocalDate.now().minusMonths(6);
        List<Transaction> transactions = transactionRepository
                .findByUserAndTransactionDateBetween(user, sixMonthsAgo, LocalDate.now());
        
        // Calculate financial metrics
        BigDecimal totalIncome = transactions.stream()
                .filter(t -> t.getType() == TransactionType.INCOME)
                .map(Transaction::getAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        BigDecimal totalExpense = transactions.stream()
                .filter(t -> t.getType() == TransactionType.EXPENSE)
                .map(Transaction::getAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        BigDecimal monthlyIncome = totalIncome.divide(BigDecimal.valueOf(6), 2, RoundingMode.HALF_UP);
        BigDecimal monthlyExpense = totalExpense.divide(BigDecimal.valueOf(6), 2, RoundingMode.HALF_UP);
        BigDecimal monthlySavings = monthlyIncome.subtract(monthlyExpense);
        
        // Get existing investments
        List<Investment> investments = investmentRepository.findByUser(user);
        BigDecimal totalInvested = investments.stream()
                .map(Investment::getAmountInvested)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        BigDecimal totalCurrentValue = investments.stream()
                .map(Investment::getCurrentValue)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        BigDecimal totalReturns = BigDecimal.ZERO;
        if (totalInvested.compareTo(BigDecimal.ZERO) > 0) {
            totalReturns = totalCurrentValue.subtract(totalInvested)
                    .multiply(new BigDecimal("100"))
                    .divide(totalInvested, 2, RoundingMode.HALF_UP);
        }
        
        StringBuilder data = new StringBuilder();
        data.append("=== USER FINANCIAL PROFILE ===\n");
        data.append(String.format("Monthly Income: ₹%.2f\n", monthlyIncome));
        data.append(String.format("Monthly Expenses: ₹%.2f\n", monthlyExpense));
        data.append(String.format("Monthly Savings: ₹%.2f\n", monthlySavings));
        data.append(String.format("Existing Investments: ₹%.2f\n", totalInvested));
        data.append(String.format("Investment Returns: %.1f%%\n", totalReturns));
        data.append(String.format("Risk Tolerance (1-10): %.1f\n", request.getRiskTolerance()));
        data.append(String.format("Investment Horizon (years): %.0f\n", request.getInvestmentHorizon()));
        data.append(String.format("Monthly Investment Capacity: ₹%.2f\n", request.getMonthlyInvestmentCapacity()));
        data.append(String.format("Goal: %s\n", request.getGoal()));
        
        return data.toString();
    }
    
    private String buildInvestmentPrompt(String financialData, InvestmentAdviceRequest request) {
        return String.format("""
            You are an expert financial advisor AI. Based on the user's financial profile below, 
            provide personalized investment advice.
            
            %s
            
            Return ONLY valid JSON in this exact format (no other text):
            {
                "riskProfile": "ONE OF: CONSERVATIVE, MODERATELY CONSERVATIVE, MODERATE, MODERATELY AGGRESSIVE, AGGRESSIVE",
                "expectedAnnualReturns": number,
                "portfolioAllocation": [
                    {"assetClass": "Stocks", "percentage": number, "examples": "Large-cap, Index funds"},
                    {"assetClass": "Bonds", "percentage": number, "examples": "Government bonds"},
                    {"assetClass": "Cash", "percentage": number, "examples": "Savings, FD"}
                ],
                "recommendations": ["Recommendation 1", "Recommendation 2", "Recommendation 3", "Recommendation 4", "Recommendation 5"],
                "projectedGrowth": {
                    "totalInvestment": number,
                    "estimatedReturns": number,
                    "futureValue": number
                },
                "summary": "2-3 sentence personalized summary of the advice"
            }
            
            Important rules:
            1. Risk profile must match their risk tolerance and horizon
            2. Portfolio allocation percentages must add to 100
            3. Expected returns should be realistic (5-15%%)
            4. Recommendations should be practical and actionable
            5. Be conservative and responsible in advice
            """,
            financialData);
    }
    
    private String callOpenRouterAPI(String prompt) {
        try {
            String url = "https://openrouter.ai/api/v1/chat/completions";
            
            Map<String, Object> requestBody = new LinkedHashMap<>();
            requestBody.put("model", openRouterModel);
            
            List<Map<String, String>> messages = new ArrayList<>();
            
            Map<String, String> systemMessage = new LinkedHashMap<>();
            systemMessage.put("role", "system");
            systemMessage.put("content", "You are a professional financial advisor AI. Always respond with valid JSON only.");
            messages.add(systemMessage);
            
            Map<String, String> userMessage = new LinkedHashMap<>();
            userMessage.put("role", "user");
            userMessage.put("content", prompt);
            messages.add(userMessage);
            
            requestBody.put("messages", messages);
            requestBody.put("temperature", 0.3);
            requestBody.put("max_tokens", 1500);
            
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.set("Authorization", "Bearer " + apiKey);
            headers.set("HTTP-Referer", "http://localhost:8080");
            headers.set("X-Title", "Finance AI Platform");
            
            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, headers);
            
            System.out.println("Calling OpenRouter for investment advice...");
            ResponseEntity<String> response = restTemplate.exchange(
                url, HttpMethod.POST, entity, String.class);
            
            if (response.getStatusCode() == HttpStatus.OK) {
                JsonNode json = objectMapper.readTree(response.getBody());
                String content = json.path("choices").get(0).path("message").path("content").asText();
                System.out.println("AI response received");
                return content;
            } else {
                throw new RuntimeException("API returned " + response.getStatusCode());
            }
            
        } catch (Exception e) {
            throw new RuntimeException("AI API call failed: " + e.getMessage());
        }
    }
    
    private InvestmentAdviceResponse parseAIResponse(String aiResponse, InvestmentAdviceRequest request) {
        try {
            // Clean the response
            String cleanJson = aiResponse.replaceAll("```json\\n?", "").replaceAll("```\\n?", "").trim();
            
            int startIdx = cleanJson.indexOf("{");
            int endIdx = cleanJson.lastIndexOf("}");
            if (startIdx >= 0 && endIdx > startIdx) {
                cleanJson = cleanJson.substring(startIdx, endIdx + 1);
            }
            
            JsonNode jsonNode = objectMapper.readTree(cleanJson);
            
            InvestmentAdviceResponse response = new InvestmentAdviceResponse();
            
            // Set risk profile
            response.setRiskProfile(jsonNode.has("riskProfile") ? 
                jsonNode.get("riskProfile").asText() : "MODERATE");
            
            // Set expected returns
            response.setExpectedAnnualReturns(jsonNode.has("expectedAnnualReturns") ? 
                new BigDecimal(jsonNode.get("expectedAnnualReturns").asText()) : new BigDecimal("10"));
            
            // Set recommended monthly investment
            response.setRecommendedMonthlyInvestment(request.getMonthlyInvestmentCapacity());
            
            // Parse portfolio allocation
            List<PortfolioAllocation> allocations = new ArrayList<>();
            if (jsonNode.has("portfolioAllocation") && jsonNode.get("portfolioAllocation").isArray()) {
                for (JsonNode alloc : jsonNode.get("portfolioAllocation")) {
                    String assetClass = alloc.has("assetClass") ? alloc.get("assetClass").asText() : "Unknown";
                    BigDecimal percentage = alloc.has("percentage") ? 
                        new BigDecimal(alloc.get("percentage").asText()) : BigDecimal.ZERO;
                    String examples = alloc.has("examples") ? alloc.get("examples").asText() : "";
                    allocations.add(new PortfolioAllocation(assetClass, percentage, examples));
                }
            }
            response.setPortfolioAllocation(allocations);
            
            // Parse recommendations
            List<String> recommendations = new ArrayList<>();
            if (jsonNode.has("recommendations") && jsonNode.get("recommendations").isArray()) {
                for (JsonNode rec : jsonNode.get("recommendations")) {
                    recommendations.add(rec.asText());
                }
            }
            response.setRecommendations(recommendations);
            
            // Parse projected growth
            Map<String, BigDecimal> projectedGrowth = new HashMap<>();
            if (jsonNode.has("projectedGrowth")) {
                JsonNode growth = jsonNode.get("projectedGrowth");
                projectedGrowth.put("totalInvestment", growth.has("totalInvestment") ? 
                    new BigDecimal(growth.get("totalInvestment").asText()) : BigDecimal.ZERO);
                projectedGrowth.put("estimatedReturns", growth.has("estimatedReturns") ? 
                    new BigDecimal(growth.get("estimatedReturns").asText()) : BigDecimal.ZERO);
                projectedGrowth.put("futureValue", growth.has("futureValue") ? 
                    new BigDecimal(growth.get("futureValue").asText()) : BigDecimal.ZERO);
            } else {
                // Calculate fallback projection
                projectedGrowth = calculateFallbackProjection(request);
            }
            addYearlyProjection(projectedGrowth, request, response.getExpectedAnnualReturns());
            response.setProjectedGrowth(projectedGrowth);
            
            // Set summary
            response.setSummary(jsonNode.has("summary") ? 
                jsonNode.get("summary").asText() : "AI-generated investment advice based on your profile.");
            response.setMethodUsed("AI");
            
            return response;
            
        } catch (Exception e) {
            System.err.println("Failed to parse AI response: " + e.getMessage());
            throw new RuntimeException("Failed to parse AI response");
        }
    }
    
    private Map<String, BigDecimal> calculateFallbackProjection(InvestmentAdviceRequest request) {
        Map<String, BigDecimal> projection = new HashMap<>();
        
        BigDecimal monthlyInvestment = request.getMonthlyInvestmentCapacity();
        BigDecimal years = request.getInvestmentHorizon();
        BigDecimal annualReturns = new BigDecimal("10");
        
        BigDecimal totalInvestment = monthlyInvestment.multiply(new BigDecimal("12")).multiply(years);
        BigDecimal monthlyRate = annualReturns.divide(new BigDecimal("1200"), 4, RoundingMode.HALF_UP);
        BigDecimal months = years.multiply(new BigDecimal("12"));
        
        BigDecimal onePlusR = BigDecimal.ONE.add(monthlyRate);
        BigDecimal power = BigDecimal.valueOf(Math.pow(onePlusR.doubleValue(), months.doubleValue()));
        BigDecimal futureValue = monthlyInvestment
                .multiply(power.subtract(BigDecimal.ONE))
                .divide(monthlyRate, 2, RoundingMode.HALF_UP)
                .multiply(onePlusR);
        
        projection.put("totalInvestment", totalInvestment);
        projection.put("estimatedReturns", futureValue.subtract(totalInvestment));
        projection.put("futureValue", futureValue);
        addYearlyProjection(projection, request, annualReturns);
        
        return projection;
    }

    private void addYearlyProjection(Map<String, BigDecimal> projection, InvestmentAdviceRequest request, BigDecimal annualReturns) {
        if (request.getMonthlyInvestmentCapacity() == null || request.getInvestmentHorizon() == null) {
            return;
        }

        BigDecimal monthlyInvestment = request.getMonthlyInvestmentCapacity();
        BigDecimal monthlyRate = annualReturns.divide(new BigDecimal("1200"), 8, RoundingMode.HALF_UP);
        int years = Math.max(1, request.getInvestmentHorizon().intValue());

        for (int year = 1; year <= years; year++) {
            BigDecimal months = BigDecimal.valueOf(year * 12L);
            BigDecimal futureValue;

            if (monthlyRate.compareTo(BigDecimal.ZERO) == 0) {
                futureValue = monthlyInvestment.multiply(months);
            } else {
                BigDecimal onePlusR = BigDecimal.ONE.add(monthlyRate);
                BigDecimal power = BigDecimal.valueOf(Math.pow(onePlusR.doubleValue(), months.doubleValue()));
                futureValue = monthlyInvestment
                        .multiply(power.subtract(BigDecimal.ONE))
                        .divide(monthlyRate, 2, RoundingMode.HALF_UP)
                        .multiply(onePlusR);
            }

            projection.putIfAbsent("year" + year, futureValue);
        }
    }


        
    /**
     * Get investment advice for a user
     */
    public String getInvestmentAdvice(Long userId) {
        try {
            List<Investment> investments = investmentRepository.findByUser(
                userRepository.findById(userId).orElse(null));
            
            if (investments == null || investments.isEmpty()) {
                return "You don't have any investments yet. Consider starting with mutual funds or index funds for long-term growth.";
            }
            
            BigDecimal totalInvested = investments.stream()
                .map(Investment::getAmountInvested)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
            
            BigDecimal totalCurrentValue = investments.stream()
                .map(Investment::getCurrentValue)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
            
            BigDecimal totalReturns = totalCurrentValue.subtract(totalInvested);
            BigDecimal returnsPercentage = BigDecimal.ZERO;
            
            if (totalInvested.compareTo(BigDecimal.ZERO) > 0) {
                returnsPercentage = totalReturns.multiply(new BigDecimal("100"))
                    .divide(totalInvested, 2, java.math.RoundingMode.HALF_UP);
            }
            
            StringBuilder advice = new StringBuilder();
            advice.append(String.format("• **Total Invested:** ₹%s\n", totalInvested.toPlainString()));
            advice.append(String.format("• **Current Value:** ₹%s\n", totalCurrentValue.toPlainString()));
            advice.append(String.format("• **Total Returns:** ₹%s (%.1f%%)\n", 
                totalReturns.toPlainString(), returnsPercentage));
            advice.append("\n");
            
            if (returnsPercentage.compareTo(BigDecimal.ZERO) > 0) {
                advice.append("✅ Your portfolio is performing well! ");
                if (returnsPercentage.compareTo(new BigDecimal("15")) > 0) {
                    advice.append("Excellent returns! Consider taking some profits if needed.");
                } else {
                    advice.append("Keep up the consistent investment strategy.");
                }
            } else if (returnsPercentage.compareTo(BigDecimal.ZERO) < 0) {
                advice.append("⚠️ Your portfolio is currently down. Consider diversifying or holding for long-term recovery.");
            } else {
                advice.append("📊 Your investments are breaking even. Consider reviewing your portfolio allocation.");
            }
            
            return advice.toString();
            
        } catch (Exception e) {
            return "Unable to fetch investment data. Please ensure your investments are properly added.";
        }
    }

    
}
